$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    autoplay: true,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:5
        }
    }
})

function drama(){
    document.getElementById("2").style.border="1px solid grey"
    document.getElementById("1").style.border="none";
    document.getElementById("3").style.border="none";
    document.getElementById("4").style.border="none";
    document.getElementById("5").style.border="none";
    document.getElementById("6").style.border="none";
    document.getElementById("7").style.border="none";
    document.getElementById("8").style.border="none";
    document.getElementById("9").style.border="none";
    document.getElementById("10").style.border="none";
    document.getElementById("11").style.border="none";
    document.getElementById("12").style.border="none";
    document.getElementById("drama").style.display="inline";
    document.getElementById("comedy").style.display="none";
    document.getElementById("action").style.display="none";
    document.getElementById("romance").style.display="none";
    document.getElementById("horror").style.display="none";
    document.getElementById("fantasy").style.display="none";
    document.getElementById("scifi").style.display="none";
    document.getElementById("thriller").style.display="none";
    document.getElementById("western").style.display="none";
    document.getElementById("adventure").style.display="none";
    document.getElementById("animation").style.display="none";
    document.getElementById("documentary").style.display="none";
}
function comedy(){
    document.getElementById("1").style.border="1px solid grey"
    document.getElementById("2").style.border="none";
    document.getElementById("3").style.border="none";
    document.getElementById("4").style.border="none";
    document.getElementById("5").style.border="none";
    document.getElementById("6").style.border="none";
    document.getElementById("7").style.border="none";
    document.getElementById("8").style.border="none";
    document.getElementById("9").style.border="none";
    document.getElementById("10").style.border="none";
    document.getElementById("11").style.border="none";
    document.getElementById("12").style.border="none";
    document.getElementById("drama").style.display="none";
    document.getElementById("comedy").style.display="inline";
    document.getElementById("action").style.display="none";
    document.getElementById("romance").style.display="none";
    document.getElementById("horror").style.display="none";
    document.getElementById("fantasy").style.display="none";
    document.getElementById("scifi").style.display="none";
    document.getElementById("thriller").style.display="none";
    document.getElementById("western").style.display="none";
    document.getElementById("adventure").style.display="none";
    document.getElementById("animation").style.display="none";
    document.getElementById("documentary").style.display="none";
}
function action(){
    document.getElementById("5").style.border="1px solid grey"
    document.getElementById("1").style.border="none";
    document.getElementById("2").style.border="none";
    document.getElementById("3").style.border="none";
    document.getElementById("4").style.border="none";
    document.getElementById("6").style.border="none";
    document.getElementById("7").style.border="none";
    document.getElementById("8").style.border="none";
    document.getElementById("9").style.border="none";
    document.getElementById("10").style.border="none";
    document.getElementById("11").style.border="none";
    document.getElementById("12").style.border="none";
    document.getElementById("drama").style.display="none";
    document.getElementById("comedy").style.display="none";
    document.getElementById("action").style.display="inline";
    document.getElementById("romance").style.display="none";
    document.getElementById("horror").style.display="none";
    document.getElementById("fantasy").style.display="none";
    document.getElementById("scifi").style.display="none";
    document.getElementById("thriller").style.display="none";
    document.getElementById("western").style.display="none";
    document.getElementById("adventure").style.display="none";
    document.getElementById("animation").style.display="none";
    document.getElementById("documentary").style.display="none";
}
function romance(){
    document.getElementById("9").style.border="1px solid grey"
    document.getElementById("1").style.border="none";
    document.getElementById("2").style.border="none";
    document.getElementById("3").style.border="none";
    document.getElementById("4").style.border="none";
    document.getElementById("5").style.border="none";
    document.getElementById("6").style.border="none";
    document.getElementById("7").style.border="none";
    document.getElementById("8").style.border="none";
    document.getElementById("10").style.border="none";
    document.getElementById("11").style.border="none";
    document.getElementById("12").style.border="none";
    document.getElementById("drama").style.display="none";
    document.getElementById("comedy").style.display="none";
    document.getElementById("action").style.display="none";
    document.getElementById("romance").style.display="inline";
    document.getElementById("horror").style.display="none";
    document.getElementById("fantasy").style.display="none";
    document.getElementById("scifi").style.display="none";
    document.getElementById("thriller").style.display="none";
    document.getElementById("western").style.display="none";
    document.getElementById("adventure").style.display="none";
    document.getElementById("animation").style.display="none";
    document.getElementById("documentary").style.display="none";
}
function horror(){
    document.getElementById("7").style.border="1px solid grey"
    document.getElementById("1").style.border="none";
    document.getElementById("2").style.border="none";
    document.getElementById("3").style.border="none";
    document.getElementById("4").style.border="none";
    document.getElementById("5").style.border="none";
    document.getElementById("6").style.border="none";
    document.getElementById("8").style.border="none";
    document.getElementById("9").style.border="none";
    document.getElementById("10").style.border="none";
    document.getElementById("11").style.border="none";
    document.getElementById("12").style.border="none";
    document.getElementById("drama").style.display="none";
    document.getElementById("comedy").style.display="none";
    document.getElementById("action").style.display="none";
    document.getElementById("romance").style.display="none";
    document.getElementById("horror").style.display="inline";
    document.getElementById("fantasy").style.display="none";
    document.getElementById("scifi").style.display="none";
    document.getElementById("thriller").style.display="none";
    document.getElementById("western").style.display="none";
    document.getElementById("adventure").style.display="none";
    document.getElementById("animation").style.display="none";
    document.getElementById("documentary").style.display="none";
}
function fantasy(){
    document.getElementById("3").style.border="1px solid grey"
    document.getElementById("1").style.border="none";
    document.getElementById("2").style.border="none";
    document.getElementById("4").style.border="none";
    document.getElementById("5").style.border="none";
    document.getElementById("6").style.border="none";
    document.getElementById("7").style.border="none";
    document.getElementById("8").style.border="none";
    document.getElementById("9").style.border="none";
    document.getElementById("10").style.border="none";
    document.getElementById("11").style.border="none";
    document.getElementById("12").style.border="none";
    document.getElementById("drama").style.display="none";
    document.getElementById("comedy").style.display="none";
    document.getElementById("action").style.display="none";
    document.getElementById("romance").style.display="none";
    document.getElementById("horror").style.display="none";
    document.getElementById("fantasy").style.display="inline";
    document.getElementById("scifi").style.display="none";
    document.getElementById("thriller").style.display="none";
    document.getElementById("western").style.display="none";
    document.getElementById("adventure").style.display="none";
    document.getElementById("animation").style.display="none";
    document.getElementById("documentary").style.display="none";
}
function scifi(){
    document.getElementById("8").style.border="1px solid grey"
    document.getElementById("1").style.border="none";
    document.getElementById("2").style.border="none";
    document.getElementById("3").style.border="none";
    document.getElementById("4").style.border="none";
    document.getElementById("5").style.border="none";
    document.getElementById("6").style.border="none";
    document.getElementById("7").style.border="none";
    document.getElementById("9").style.border="none";
    document.getElementById("10").style.border="none";
    document.getElementById("11").style.border="none";
    document.getElementById("12").style.border="none";
    document.getElementById("drama").style.display="none";
    document.getElementById("comedy").style.display="none";
    document.getElementById("action").style.display="none";
    document.getElementById("romance").style.display="none";
    document.getElementById("horror").style.display="none";
    document.getElementById("fantasy").style.display="none";
    document.getElementById("scifi").style.display="inline";
    document.getElementById("thriller").style.display="none";
    document.getElementById("western").style.display="none";
    document.getElementById("adventure").style.display="none";
    document.getElementById("animation").style.display="none";
    document.getElementById("documentary").style.display="none";
}
function thriller(){
    document.getElementById("6").style.border="1px solid grey"
    document.getElementById("1").style.border="none";
    document.getElementById("2").style.border="none";
    document.getElementById("3").style.border="none";
    document.getElementById("4").style.border="none";
    document.getElementById("5").style.border="none";
    document.getElementById("7").style.border="none";
    document.getElementById("8").style.border="none";
    document.getElementById("9").style.border="none";
    document.getElementById("10").style.border="none";
    document.getElementById("11").style.border="none";
    document.getElementById("12").style.border="none";
    document.getElementById("drama").style.display="none";
    document.getElementById("comedy").style.display="none";
    document.getElementById("action").style.display="none";
    document.getElementById("romance").style.display="none";
    document.getElementById("horror").style.display="none";
    document.getElementById("fantasy").style.display="none";
    document.getElementById("scifi").style.display="none";
    document.getElementById("thriller").style.display="inline";
    document.getElementById("western").style.display="none";
    document.getElementById("adventure").style.display="none";
    document.getElementById("animation").style.display="none";
    document.getElementById("documentary").style.display="none";
}
function western(){
    document.getElementById("10").style.border="1px solid grey";
    document.getElementById("1").style.border="none";
    document.getElementById("2").style.border="none";
    document.getElementById("3").style.border="none";
    document.getElementById("4").style.border="none";
    document.getElementById("5").style.border="none";
    document.getElementById("6").style.border="none";
    document.getElementById("7").style.border="none";
    document.getElementById("8").style.border="none";
    document.getElementById("9").style.border="none";
    document.getElementById("11").style.border="none";
    document.getElementById("12").style.border="none";
    document.getElementById("drama").style.display="none";
    document.getElementById("comedy").style.display="none";
    document.getElementById("action").style.display="none";
    document.getElementById("romance").style.display="none";
    document.getElementById("horror").style.display="none";
    document.getElementById("fantasy").style.display="none";
    document.getElementById("scifi").style.display="none";
    document.getElementById("thriller").style.display="none";
    document.getElementById("western").style.display="inline";
    document.getElementById("adventure").style.display="none";
    document.getElementById("animation").style.display="none";
    document.getElementById("documentary").style.display="none";
}
function adventure(){
    document.getElementById("11").style.border="1px solid grey"
    document.getElementById("1").style.border="none";
    document.getElementById("2").style.border="none";
    document.getElementById("3").style.border="none";
    document.getElementById("4").style.border="none";
    document.getElementById("5").style.border="none";
    document.getElementById("6").style.border="none";
    document.getElementById("7").style.border="none";
    document.getElementById("8").style.border="none";
    document.getElementById("9").style.border="none";
    document.getElementById("10").style.border="none";
    document.getElementById("12").style.border="none";
    document.getElementById("drama").style.display="none";
    document.getElementById("comedy").style.display="none";
    document.getElementById("action").style.display="none";
    document.getElementById("romance").style.display="none";
    document.getElementById("horror").style.display="none";
    document.getElementById("fantasy").style.display="none";
    document.getElementById("scifi").style.display="none";
    document.getElementById("thriller").style.display="none";
    document.getElementById("western").style.display="none";
    document.getElementById("adventure").style.display="inline";
    document.getElementById("animation").style.display="none";
    document.getElementById("documentary").style.display="none";
}
function animation(){
    document.getElementById("4").style.border="1px solid grey"
    document.getElementById("1").style.border="none";
    document.getElementById("2").style.border="none";
    document.getElementById("3").style.border="none";
    document.getElementById("5").style.border="none";
    document.getElementById("6").style.border="none";
    document.getElementById("7").style.border="none";
    document.getElementById("8").style.border="none";
    document.getElementById("9").style.border="none";
    document.getElementById("10").style.border="none";
    document.getElementById("11").style.border="none";
    document.getElementById("12").style.border="none";
    document.getElementById("drama").style.display="none";
    document.getElementById("comedy").style.display="none";
    document.getElementById("action").style.display="none";
    document.getElementById("romance").style.display="none";
    document.getElementById("horror").style.display="none";
    document.getElementById("fantasy").style.display="none";
    document.getElementById("scifi").style.display="none";
    document.getElementById("thriller").style.display="none";
    document.getElementById("western").style.display="none";
    document.getElementById("adventure").style.display="none";
    document.getElementById("animation").style.display="inline";
    document.getElementById("documentary").style.display="none";
}
function documentary(){
    document.getElementById("12").style.border="1px solid grey";
    document.getElementById("1").style.border="none";
    document.getElementById("2").style.border="none";
    document.getElementById("3").style.border="none";
    document.getElementById("4").style.border="none";
    document.getElementById("5").style.border="none";
    document.getElementById("6").style.border="none";
    document.getElementById("7").style.border="none";
    document.getElementById("8").style.border="none";
    document.getElementById("9").style.border="none";
    document.getElementById("10").style.border="none";
    document.getElementById("11").style.border="none";
    document.getElementById("drama").style.display="none";
    document.getElementById("comedy").style.display="none";
    document.getElementById("action").style.display="none";
    document.getElementById("romance").style.display="none";
    document.getElementById("horror").style.display="none";
    document.getElementById("fantasy").style.display="none";
    document.getElementById("scifi").style.display="none";
    document.getElementById("thriller").style.display="none";
    document.getElementById("western").style.display="none";
    document.getElementById("adventure").style.display="none";
    document.getElementById("animation").style.display="none";
    document.getElementById("documentary").style.display="inline";
}